version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

# Uncomment below to add a mock SMTP server for email testing
#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "8025:8025"
